### ISSUE TITLE
Cache prepared statements

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#109]
I'm not sure if this actually improves performance or now, so it might be useless

Moved from https://github.com/ajayyy/SponsorBlock/issues/102

**Comment by Joe-Dowd** [comment]
I think there's something here if combined with the youtube api to get publish time. Not using it as a source of truth but purely as a cacheing system for old videos unlikely to get new submissions
 - If video is more than x days old, allow cacheing (or assume allow on failure to get publish time)
 - If video has no submissions create an eternal entry saying so (invalidated on submission)
 - If video has got submissions, create a timed entry (to reduce cache storage due the fact we wont be getting repeated 404 requests from users)

This would help with the continued request for submissions on 404, only querying the database if somebody has actually interacted with the video.

This would still allow people to download the database and access all information, but ease the sqlite bottleneck (with the cache values being more malleable than what cloud flare provides.

**Comment by ajayyy** [comment]
Those are good ideas. This issue was about caching the `db.prepare("query")` statements. Example:

```
let getSegments = db.prepare("query");


//...

function skipSegments() {
    let segments = getSegments.get(videoID);

//...
```

It'll be a little different now that there is the mysql support and the queries are a little different. I've just read that apparently compiling prepare statements can take a bit of time.

**Comment by Joe-Dowd** [comment]
I was thinking stick it when the request is received - so cache the user response with a key of category list and video id
