### ISSUE TITLE
return valid JSON response on 404 on skipSegments/:sha256HashPrefix

### ISSUE THREAD

**Issue by girst** [ajayyy/SponsorBlockServer#150]
Currently, requesting a prefix with 0 known video IDs returns a 404 error with response body text "Not Found". It would make more sense if it were to return `[]` (empty array).

**Comment by Joe-Dowd** [comment]
404 code with empty array body? Or 200 with an empty array body?

**Comment by girst** [comment]
On Wed, Sep 30, 2020 at 04:58:24PM -0700, Joe Dowd wrote:
>404 code with empty array body? Or 200 with an empty array body?

404 seems semantically more correct, but I personally don't have a 
strong opinion about it.
