### ISSUE TITLE
VIP segment time shift

### ISSUE THREAD

**Issue by MRuy** [ajayyy/SponsorBlockServer#151]
How about adding a functionality that can shift segments **startTime** and **endTime** of a video by providing a **timestamp** and a **duration** in seconds to adjust the existing segments.

Use case:
Videos or livestreams that got edited after the segments got submitted.

**Comment by MRuy** [comment]
Legend:

-   ------- Timeline
-   ####### Segment
-  +++++ Segment inside cut out
-   [_____] Cut out
-   "timestamp" = Time in seconds where the cut happend
-   "duration" = Time in seconds that got removed


1. Cut before segment
   -------[______]--############--------------------
   Adjust startTime and EndTime: startTime - duration, endTime - duration

2. Cut after segment
   -----------------############--[______]----------
   No adjustment needed (for this segment)

3. Cut inside segment
   -----------------##[++++]####--------------------
   Adjust endTime to: endTime - duration

4. Cut overlap startTime
   -------------[____++]########--------------------
   Adjust startTime and endTime: startTime = timestamp, endTime - duration

5. Cut overlap endTime
   -----------------########[++____]----------------
   Adjust endTime to: endTime = timestamp

6. Cut overlap segment (100%)
   --------------[__++++++++___]----------------
   Remove segment

**Comment by ajayyy** [comment]
I see, but keeping the duration?

**Comment by MRuy** [comment]
# Example 1 (Cut between 2 segments)
![segmentshift-example](https://user-images.githubusercontent.com/1896243/94977201-079cc280-0518-11eb-930f-b58adccbac84.png)
# Example 2 (Cut that removes part of the segment beginning)
![segmentshift-example2](https://user-images.githubusercontent.com/1896243/94977202-08355900-0518-11eb-825b-d33ca720d6d6.png)

**Comment by MRuy** [comment]
Here is a browser version:
https://www.mruy.de/tmp/segmentShift.html

You can define the startTime and endTime of the "video" cut like normal segments and see how the segments get adjusted.
(Timeline is not adjusting in this demonstration (not important for the server version))

**Comment by Joe-Dowd** [comment]
i like it as a way to handle livestream cuts, however the youtube api (in my limited experience) isn't to good at distinguishing livestreams from regular videos, making it hard to automatically moderate these submissions on the server side.
