### ISSUE TITLE
IP hashing not secure

### ISSUE THREAD

**Issue by tazitus** [ajayyy/SponsorBlockServer#16]
There are only 2^32 IPv4 addresses, so in order to decrypt one IP address in the database (hashed 5000 times), you would need to calculate a maximum of 2^32 * 5000 SHA256 hashes.

[An Nvidia GTX 1080 can apparently calculate 2829.7 * 10^6 of those per second](https://gist.github.com/epixoip/6ee29d5d626bd8dfe671a2d8f188b77b):  
(2^32 * 5000) / (2829.7 * 10^6) = 7589 seconds = 2.1 hours

[An AntMiner S9 can even do 14 * 10^12 double SHA256 hashes per second](https://en.bitcoin.it/wiki/Mining_hardware_comparison):  
(2^32 * 5000) / (14 * 10^12 * 2) = 0.77 seconds

Also, with the salt being global, you can essentially decrypt not only one, but all IP addresses in the database in that time.

**Comment by OfficialNoob** [comment]
I have told @ajayyy before about this.
 IP based rate limiting is not that effective anyway.
Also can a AntMiner S9 crack this kind of hash as I think it uses an ASIC

**Comment by ajayyy** [comment]
Yup, database is private now.
