### ISSUE TITLE
Add new API endpoints to wiki

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#167]
`deleteNoSegments`

`getUserInfo`

`segmentShift`

**Comment by MRuy** [comment]
[API-Docs.md](https://github.com/ajayyy/SponsorBlockServer/files/6594464/API-Docs.md)  

* Renamed: POST `/api/noSegments` to `/api/lockCategories`
* Added: DELETE `/api/lockCategories`

* `/api/userInfo` already exists
* `segmentShift` was discussed for removing

**Comment by ajayyy** [comment]
Thanks!
