### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by FACF302** [ajayyy/SponsorBlockServer#183]
{"cplatform":"mobile","cbr":"com.vanced.android.apps.youtube.music","c":"android_music","cmodel":"SM-A207M","cos":"Android","csdk":"29","cbrver":"4.02.51","cver":"4.02.51","cosver":"10.QP1A.190711.020.A207MUBU2BTH1","cbrand":"samsung","fmt":"N\/A","afmt":"N\/A","bh":0,"conn":3,"volume":100,"loudness":"0.000","bat":"0.320:0","df":"0\/0","time":"2020-11-15T22:41:28.575Z","mtext":"","error":"No errors","logged_in":"1","e":"23944779,23956635,23961732,23971345,23951620,23962882,23885574,23951634,23912909,24590302,23744176,23965505,23962434,23955372,23880043,23723208,23967171,23916388,23934522,23970386,23958692,23966727,23882685,23934970,23954390,23880664,23897655,24590289,23969634,23918597,23748147,23963931,23946420,1714246,23950597,23884386,23942338,23967042,23948841,23839597"}

**Comment by ajayyy** [comment]
What does this mean?
