### ISSUE TITLE
Support for alternative sites

### ISSUE THREAD

**Issue by dioio-io** [ajayyy/SponsorBlockServer#192]
Add a new variable
"host" or "service", which would be an identifiable code for sites other than youtube

i.e:

```js
{
  host: string, // Defaults to youtube, See [services list] // <---
  videoID: string,
  category: string, // Optional, defaults to "sponsor". See [the category list]
  categories: string[] // Optional. Use instead of "category" if you want multiple categories. Will look like ["sponsor","intro"]
}
```

This would allow to later extend the main extension to support LBRY, bitchute, etc.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/515

**Comment by ajayyy** [comment]
I was thinking of going with the name "service"

**Comment by dioio-io** [comment]
Should we have the issue open here to handle and decide on the server side implementation first?

**Comment by ajayyy** [comment]
I guess we can have both

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlockServer/pull/215
