### ISSUE TITLE
Server timeout when sending invalid categories parameter with sha256'ed videoId

### ISSUE THREAD

**Issue by willemstuursma** [ajayyy/SponsorBlockServer#213]
I ran into a server timeout when accessing this URL:

`https://sponsor.ajay.app/api/skipSegments/e4c0?categories=sponsor`.

Without the `categories` parameter it works fine and the server responds quickly. Also with the categories JSON encoded in an array it works fine. 

PS this is for video id `cd4ILT8LDoI`.

**Comment by origeva** [comment]
This endpoint accepts the categories  prameter as a string array in the following format ?categories=["sponsor","intro","outro"]
Notice the default category is sponsor so you could leave out the categories parameter.
Try the following:
(First two return the same)
https://sponsor.ajay.app/api/skipSegments/e4c0

https://sponsor.ajay.app/api/skipSegments/e4c0?categories=["sponsor"]

https://sponsor.ajay.app/api/skipSegments/e4c0?categories=["sponsor","intro"]

**Comment by willemstuursma** [comment]
Thanks. Passing categories as a JSON encoded array did work. 

However, I guess passing invalid JSON or not an array can still cause a DOS. I'll update the issue to reflect that.

**Comment by MRuy** [comment]
The problem should be fixed with this PR https://github.com/ajayyy/SponsorBlockServer/pull/209

Maybe the server is not running on the latest version

**Comment by ajayyy** [comment]
Yep, will be fixed next deploy
