### ISSUE TITLE
[Feature request] Archive down voted segments

### ISSUE THREAD

**Issue by MRuy** [ajayyy/SponsorBlockServer#221]
Move down voted segments (-2) to a archive table, after X days, for performance improvement.  
It should make the indexes on the table sponsorTimes smaller which will reduce the memory and CPU consumption

**Comment by HaiDang666** [comment]
can I work on this?

**Comment by ajayyy** [comment]
You should be able to make comment saying `.take` now btw

**Comment by ajayyy** [comment]
lol, like that
