### ISSUE TITLE
invidious.fdn.fr should not be trusted.

### ISSUE THREAD

**Issue by NDevTK** [ajayyy/SponsorBlockServer#225]
Hi, @ajayyy
https://github.com/ajayyy/SponsorBlockServer/blob/master/nginx/nginx.conf#L66 has a "proxy_pass" for what im guessing is a 3rd party service.
The admins of, or an XSS bug in "invidious.fdn.fr" could allow a service worker to be registered.
This would allow Session and Video IDs to be leaked and impersonation of the sponsor.ajay.app domain.

**Comment by ajayyy** [comment]
Removed in 77a4c2fe34d67002b2427d921c8599cd224ab03d, thanks!
