### ISSUE TITLE
Support repeated category URL parameter 

### ISSUE THREAD

**Issue by erdnaxeli** [ajayyy/SponsorBlockServer#235]
For the `skipSegment` route, currently we have to use `categories=["sponsor", "interaction"]` to check for multiple categories, using json in the `categories` parameter.

This looks… weird. Instead, it would be much more pleasant if we could do `category=sponsor&category=interaction`. A lot of http lib support this way for multiple values.

**Comment by origeva** [comment]
I agree it looks weird but there currently isn't a standardized way of passing an array query parameter, so it's really a matter of taste (weird is pretty subjective).
Personally I'd rather ?category=sponsor,interaction
Or the way you mentioned

**Comment by erdnaxeli** [comment]
It is not totally subjective. Some way are more supported than others.
* python requests (a vastly used http lib) does `k=v1&k=v2` : https://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls
* golang does `k=v1&k=v2` too: https://golang.org/pkg/net/url/#Values
* ruby does the same : https://ruby-doc.org/stdlib-3.0.1/libdoc/uri/rdoc/URI.html#method-c-encode_www_form
* axios (js lib) does `k[]=v1&k[]=v2`: https://stackoverflow.com/questions/49944387/how-to-correctly-use-axios-params-with-arrays
* crystal does `k=v1&k=v2`: https://crystal-lang.org/api/1.0.0/URI/Params.html#encode(hash:Hash(String,String%7CArray(String)))-class-method

`k=v1&k=v2` or `k[]=v1&k[]=v2` are common, `k=v1,v2` is less,  and I've never seen `k=["v1","v2"]` :p

**Comment by mchangrh** [comment]
This should already be possible, express handles repeated query parameter names as an array

https://expressjs.com/en/5x/api.html#req.query

this should be plug-and-play with an update to documentation
