### ISSUE TITLE
Add DELETE method to CORS

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#244]
Since #242 did not resolve it, here is the postmortem

- nginx is not adding `access-control-allow-methods` but is returning `allow`.

These two are fundamentally different. `allow` specifies which methods are accepted, `access-control-allow-methods` specifies which methods are supported over other domains (CORS) - This has to be explicitly specified by the preflight (OPTIONS) request or else the next request will fail.

The reason why DELETE is affected is because it is a non-simple HTTP request - it uses PUT or DELETE

**Comment by mchangrh** [comment]
access-control-allow methods
Present:
 - https://sponsor.ajay.app/
 - https://sponsor.ajay.app/download
 - https://cdnsponsor.ajay.app/
 
Not Present
 - https://sponsor.ajay.app/database
 - https://sponsor.ajay.app/api

**Comment by mchangrh** [comment]
Working as intended, headers are being sent for / still, probably cloudflare caching

**Comment by ajayyy** [comment]
Ah, I forgot to update the nginx config, I'll do it tomorrow if I don't forget. There is no CloudFlare infront of it anymore (except cdnsponsor)

**Comment by mchangrh** [comment]
No longer returning CORS preflight
