### ISSUE TITLE
[RFC] API Endpoints

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#246]
v0.4

## **NEW** `GET` /api/segmentInfo

Dumps all info for a segment in API form - this is a more reliable endpoint for seeing the details of a new segment in between updates on the db browser without downloading the database

input 
```js
{
  UUIDs: string[], // segments uuid - max 10
  UUID: string, // single UUID
}
```
response
```js
[{ // array of this object
  UUID: string,
  videoID: string,
  startTime: float,
  endTime: float,
  votes: int,
  incorrectVotes: int,
  locked: int,
  userID: string,
  timeSubmitted: int,
  views: int,
  category: string,
  service: string,
  videoDuration: int,
  hidden: int,
  reputation: int,
  shadowHidden: int
}]
```

## APPEND `GET` /api/userInfo

- `ignoredSegmentCount`
  - since segmentCount is all non-ignored submissions, segmentCount would remain the same to not break backwards compatibility
  - total segments can be counted by adding both up.  
- `ignoredViewCount` - same rationale as `ignoredSegmentCount` 
- `lastSegmentID` - get last segment ID
  - extremely quick glance at user history
  - see if submitting recently

Additions to response
```js
{
  ignoredSegmentCount: int,
  ignoredViewCount: int,
  lastSegmentID: string
}
```

**Comment by ajayyy** [comment]
For `getSegmentInfo`, maybe `UUID` can be an array?

**Comment by mchangrh** [comment]
Changes made, added UUID to `segmentInfo` response

**Comment by ajayyy** [comment]
looks good

**Comment by mchangrh** [comment]
v0.4 - changed `/getSegmentInfo` to take UUID (singular) or UUIDs (multiple) similar to categories from `/skipSegments`
