### ISSUE TITLE
Why does Get Skip Segments only support one category type?

### ISSUE THREAD

**Issue by ProbablePrime** [ajayyy/SponsorBlockServer#254]
https://github.com/ajayyy/SponsorBlockServer/blob/master/src/routes/getSkipSegments.ts#L273

Will bail if a get request tries to request more than one segment type in query parameters.

Why is this the case? Can this be Changed?

**Comment by ajayyy** [comment]
That is not what the code is checking for. Can you send what request you are making, maybe you are formatting it incorrectly.

**Comment by ProbablePrime** [comment]
https://sponsor.ajay.app/api/skipSegments?videoID=F10BwibIpFg&categories=[%22sponsor%22,%22intro%22]

Appears to work hmm. It did not yesterday. 

Thank you for your questions which helped me to double check my issue. I will close this issue :)
