### ISSUE TITLE
API proposal /api/categoryInfo

### ISSUE THREAD

**Issue by MRuy** [ajayyy/SponsorBlockServer#258]
# API proposal /api/categoryInfo

`categoryInfo` can be used to get the list of existing categories for client usage.  
The list can be requested with a `language` parameter (Default: en).  

Note: Maybe `language` can accept a list of languages in case the first one is not supported (example: pt-br,pt-pt,en)

`GET /api/categoryInfo?language=en`

```text
[{
  id:                 string     // used for skipSegments and voteOnSponsorTime
  color:              string     // hex color
  color_unsubmitted:  string     // hex color, used for unsubmitted segment (editor mode)
  title:              string     // Displayed title
  description:        string     // Description text
}]
```

## Special version header  

Server will send `x-sb-category-version: <version>` for clients to compare and update information via `/api/categoryInfo` if needed.

## Why?  

Clients can use new categories without code update.  
Translations and colors are available on a central API endpoint.

**Comment by ajayyy** [comment]
Maybe translation files be moved to a git submodule so that they can be used by both repositories. 

Also, to avoid confusion, let's use unsubmitted for future stuff instead of preview.

**Comment by MRuy** [comment]
* Renamed color_preview to color_unsubmitted
