### ISSUE TITLE
`Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves` error from tests on unhandled promise rejection

### ISSUE THREAD

**Issue by DetachHead** [ajayyy/SponsorBlockServer#263]
for example:
add some bad code to an async function:
```ts
export async function getSkipSegmentsByHash(req: Request, res: Response) {
    //@ts-expect-error
    const foo = asdfasdf.basdfasfd
}
```
then run tests:
![image](https://user-images.githubusercontent.com/57028336/122781521-3d2a4b80-d2f3-11eb-81cc-f0703fd23bb8.png)

this makes debugging quite difficult. spent like half an hour trying to find out what was causing it. it seems to be a problem with mocha because i just tried switching the test runner to jest and it doesn't have this problem

**Comment by mchangrh** [comment]
What's wrong with mocha? I haven't had that much difficulty writing or re-writing tests with the done() syntax.

Also jest adds a lot of dependencies compared to mocha

[25.2MB](https://packagephobia.com/result?p=jest) install vs [6.53MB](https://packagephobia.com/result?p=mocha) | [326](https://npm.anvaka.com/#/view/2d/jest) nodes vs [86](https://npm.anvaka.com/#/view/2d/mocha)

**Comment by DetachHead** [comment]
the problem is that it swallows all errors and instead just throws that timeout error, making debugging very difficult. in my opinion that's a much larger problem than the size of its dependencies.
