### ISSUE TITLE
Run unit tests with Postgres as well as sqlite on GitHub actions

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#265]
The docker-compose file can be used to set this up. `test.json` then needs to be changed to point to the postgres server. It can be done in a seperate workflow from the normal sqlite test.

Sqlite tests should be kept as it makes running tests locally a lot easier.

**Comment by mchangrh** [comment]
I have experience with docker, I can try to tackle this.

**Comment by ajayyy** [comment]
Nanobyte has discovered that the tests fail pretty badly with postgres and is looking into that

**Comment by ajayyy** [comment]
Issues were fixed in https://github.com/ajayyy/SponsorBlockServer/pull/232
