### ISSUE TITLE
Search for userIDs by partial username

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#269]
I feel like this would be useful with https://github.com/mchangrh/sb-slash/

SQL query should look similar to searching by hash. Might need to add an index just like hashedVideoID

**Comment by mchangrh** [comment]
It would be useful but I was thinking of just hosting a username mirror that is set to a much longer update time, since it's only for convenience

**Comment by mchangrh** [comment]
Yes, we could hash and add an index or just `grep partial usernames.csv`

**Comment by ajayyy** [comment]
Hashing shouldn't be needed, I think we just need to do `LIKE '%searchQuery%'`

**Comment by mchangrh** [comment]
Interesting, I didn't know you could do LIKE, thought partial/ full text was only available through mongo, I can get working on a PR

**Comment by mchangrh** [comment]
so not to name names or anything, but what's the character limit? There are usernames that are 4000 characters long

**Comment by ajayyy** [comment]
Hmm, we can probably set a limit of 64 for searching (size of sha2 hash/public userID)
