### ISSUE TITLE
Segment types

### ISSUE THREAD

**Issue by bershanskiy** [ajayyy/SponsorBlockServer#27]
As discussed earlier, there are multiple segment types besides sponsor spots. This issue tracks the API changes necessary to implement them.

There are many things that would ideally be changed, but also new features are implementable without those changes. The minimal set of changes is highlighted with **Minimal change**.

All renamings imply the creation of new API endpoints without removal of old ones methods

# Database
- **NO** Rename table `sponsorTimes` into `segmentTimes`
- [ ] **Minimal change** Add `type` ENUM column with values (to be discussed):
  - `null` -- type unknown and for backwards compatibility
  - `"intro"` -- for vide intros, usually appear before channel logo (not all channels have this)
  - `"sponsor"` -- for currently tracked sponsors
  - `"merch"` -- channel's custom merch (not an outside sponsor)
  - `"social"` -- We are on Twitter/FaceBook/etc.
  - `"buttons"` -- Comment!/Like!/Subscribe!
  - `"patreon"` -- Only for patreon.com announcements that do not contain 

Some of the categories might overlap (`"sponsor"` and `"merch"`; `"social"` and `"buttons"` and `"patreon"`), but this is intentional and enables finer granularity.

# API
- [ ] **Minimal change** To current `GET /api/postVideoSponsorTimes` add `type` which is a string (one of recognized types).
- [ ] Create `GET /api/videoSegmentTimes` to be used instead of `GET /api/getVideoSponsorTimes`
  - [ ] It sends the same data, but with `type`.
- [ ] Create `POST /api/videoSegmentTimes` to be used instead of `GET /api/postVideoSponsorTimes`
  - [ ] Use actual JSON instead of URL parameters, allow submitting multiple segments (for the same video). No mechanism for segment deletion yet. Schema:
    - `userID` -- same as now
    - `videoID` -- string, same as now
    - `segments` -- array of Objects like so:
       - `startTime` -- float, in seconds
       - `endTime` -- float, in seconds
       - `type` -- string, one of known types
- [ ] Update `GET /api/postVideoSponsorTimes` to insert `type = "sponsor"`
- [ ] Ensure `GET /api/getVideoSponsorTimes` returns only segments with `type = "sponsor"`

# NOTE: BEFORE MERGING:
You need to update the table to insert the `type` column. Since SQLLite does not have `ENUM`s, it can be `TEXT` type.
```
ALTER TABLE sponsorTimes ADD "type" TEXT;
UPDATE sponsorTimes SET "type"="sponsor";
```

**Comment by OfficialNoob** [comment]
Yeah predefined groups of categorys would be good

**Comment by OfficialNoob** [comment]
Maybe one for "off-topic"

**Comment by OfficialNoob** [comment]
Im guessing bias will be a problem even with ML

**Comment by OfficialNoob** [comment]
Why not  have different API versions like /api/v2/getVideoSponsorTime
Instead of making a new handler every time

**Comment by bershanskiy** [comment]
Ok, it has been 5 days since I posted this and all bilke-shedding is over, so I'll implement this over the weekend.

**Comment by Wombarly** [comment]
I think a `offtopic` type would be nice to have as well. 

An example usage would be to skip 10min+ sections of just fan art in Critical Role's DnD campaign videos. Although this might be able to fall under `social`?

**Comment by ajayyy** [comment]
Offtop is just too subjective for something like this
