### ISSUE TITLE
Temporary channel-specific VIP (for voting only)

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#285]
- Should be able to be added by any normal VIP
- This should only give them VIP permissions related to voting
- It will read the channel data received from the YouTube API and treat it like a VIP vote if the segment is from the correct channel
- The permission should expire after 24 hours

**Comment by RisedSky** [comment]
Why the permission should expire after 24 hours ?

**Comment by mchangrh** [comment]
.take

**Comment by mchangrh** [comment]
- store `publicID:channelID` in redis with 24h expiry
- add record of temp VIPs to private db
- change webhook title to be report by temp VIP
- lookup channelID with from YT API since it's backed by disk cache
