### ISSUE TITLE
Set up eslint

### ISSUE THREAD

**Issue by DetachHead** [ajayyy/SponsorBlockServer#290]

**Comment by ajayyy** [comment]
For the front-end side:
https://github.com/ajayyy/SponsorBlock/pull/564
https://github.com/ajayyy/SponsorBlock/pull/578

Rejecting prettier, I find it annoying.

**Comment by HaiDang666** [comment]
finally ッッッ

**Comment by mchangrh** [comment]
I can work on fixing eslint errors

**Comment by mchangrh** [comment]
Most errors fixed in #294

**Comment by mchangrh** [comment]
Should eslint be added to the CI pipeline?

**Comment by ajayyy** [comment]
I made another issue for that. I think all the issues need to be fixed first though, otherwise it will fail
