### ISSUE TITLE
Get lockCategories

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#295]
Endpoint to retrieve the current lock status of a video using a hash prefix

**Comment by mchangrh** [comment]
I can work on this, actually have a partial implementation already

**Comment by ajayyy** [comment]
Nice. I think it would be nice to include this info in the browser extenve, hence why it is with hash prefix

**Comment by mchangrh** [comment]
API proposal
`getLockCategories`
```js
{
  categories: string[]
}
```
404 on none found

`getLockCategories/:prefix`
```js
[{ // Array of this object
  "videoID": string,
  "hash":  string,
  "categories": string[]
}]
```

**Comment by mchangrh** [comment]
Post-Merge Checklist

- [ ] Update APIDocs
- [ ] Update DatabaseSchema
