### ISSUE TITLE
[RFC] Stricter ESLint rules

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#309]
currently eslint is still quite lenient, semicolons were enforced manually.
## Proposed additional rules

[no-trailing-spaces](https://eslint.org/docs/rules/no-trailing-spaces)

## RFC
[prefer-template](https://eslint.org/docs/rules/prefer-template)
```js
  `Hello, ${name}`
  // rather than
  `"Hello, "+ "name"`
 ```
[quotes](https://eslint.org/docs/rules/quotes)
single vs double quotes

[indent](https://eslint.org/docs/rules/indent)
from current code, I propose an indent of 4 spaces
```js
  "indent": ["error", 4]
```

**Comment by HaiDang666** [comment]
imo should implement commit hook

**Comment by mchangrh** [comment]
as per https://discord.com/channels/603643120093233162/607338052221665320/863853489837703209

prefer-template: yes
quotes: double
intent: 4 spaces
