### ISSUE TITLE
fix duplicate userID in userNames

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#336]
Start of discussion: https://discord.com/channels/603643120093233162/603643256714297374/872808188678910013

https://discord.com/channels/603643120093233162/603643256714297374/872876090002133052

setting UNIQUE would break few things

**Comment by mchangrh** [comment]
.take

**Comment by ajayyy** [comment]
I'm looking into it right now

**Comment by mchangrh** [comment]
`/src/routes/setUsername` L61 - probably remove LIMIT and add the usernames again

**Comment by ajayyy** [comment]
I forgot that I had an [attempted fix a few weeks ago](https://github.com/ajayyy/SponsorBlockServer/commit/83a77dfc7414e27ef82ffb40e87b4364af46e6fe). I'll see if I notice any UNIQUE query failures to see if the issue was something different
