### ISSUE TITLE
Add service category check to every table that has only videoID

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#355]
When more services are added, videoIDs may not be unique, so it should verify that the service is the same as well.

Another option is to create a new table associating each videoID and service to an identifier. This identifier can then be used everywhere else instead of having two columns. One disadvantage of this is that it would be harder to use db exports.

**Comment by HaiDang666** [comment]
I prefer the first option. Making other identifier we might have to map it back. I'll implement the category check.
