### ISSUE TITLE
re-lock segment if undovoted by VIP

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#363]
Currently, undoing a VIP downvote will leave the segment unlocked. 

- change voteOnSponsorTime L438 to < 0 since undoVote is 0
- add a secondary check if submitter is VIP and re-lock segments if undo-vote

**Comment by mchangrh** [comment]
.take

**Comment by ajayyy** [comment]
Not sure I completely agree with this. I feel if they are undoing, then they might not explicitely want it locked

**Comment by mchangrh** [comment]
fair enough, a VIP who accidentally downvoted can just as easily re-upvote to lock it.
