### ISSUE TITLE
Allow HTTP connections (i.e. do not redirect to HTTPS)

### ISSUE THREAD

**Issue by fenollp** [ajayyy/SponsorBlockServer#378]
Hi,
I'm writing a VLC plugin in Lua 5.1 and stock VLC doesn't ship with Lua librairies.
This means I cannot make HTTPS requests, only HTTP requests.

Would you be OK with dropping the automatic HTTP->HTTPS redirection?
At least only for `GET /skipSegments`

I'm unsure of the potential security issues this can open, however skipSegments does return k-anonymous results so from what I understand a MITM attack is thwarted anyway.

My other option is to bundle all the modules+SO+CAs this needs into my plugin. I'm experimenting with that still.

**Comment by ajayyy** [comment]
I'd rather not add this complexity
