### ISSUE TITLE
Count req/min using redis for server status

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#393]
Could be a useful stat, maybe paired with `(?<request>\/api\/[^\s]+?)(?:\/|$)` to find it per request type as well.

**Comment by mchangrh** [comment]
req/min is difficult, an easy metric is `instantaneous_ops_per_sec` and `hit rate`

**Comment by mchangrh** [comment]
.take

**Comment by ajayyy** [comment]
This issue wasn't necessarily getting stats about redis, I meant to use redis to store that data instead of postgres. It has an increase command which could be used I think.

**Comment by mchangrh** [comment]
what stats are stored in postgres?

**Comment by ajayyy** [comment]
none other than the calculated stuff https://sponsor.ajay.app/stats

**Comment by mchangrh** [comment]
I think I finally understand

use redis to store the number of status requests

**Comment by mchangrh** [comment]
.take
