### ISSUE TITLE
[feat] make queryCacher category specific

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#407]
Currently queryCacher is video specific and called quite frequently (any vote, new segment, shadowban)

While useful, I think the aggressiveness of the cache clearing can be turned down to be category specific and most of the underlying code is in place

Clear redis cache on 
- categoryChange if (isAble)
  - old category
  - new category
- postSkipSegment
  - target category of submission
- valid vote on segment
  - category of target
- purgeCache
  - all categories
- shadowBan
  - all selected categories

**Comment by ajayyy** [comment]
I don't think this is worth doing as we were discussing always querying all categories and then filtering out before returning the result to better handle overlapping segments. This would be combined with the new 60% overlap check.

**Comment by ajayyy** [comment]
Once we do this, we can cache thw result of the overlapping groups, instead of just the query itself. Then, all the code will need to do is the random picking if the video is in cache

**Comment by mchangrh** [comment]
wouldn't the cache be cleared when any of the segments in the cache are voted on?

**Comment by ajayyy** [comment]
yea, it would be the same clear-frequency as now

**Comment by ajayyy** [comment]
maybe it would be worth making it not clear cache in cases that don't matter? Voting on a locked segment or a video with locked categories.

**Comment by ajayyy** [comment]
Postgres cpu hasn't really been an issue anymore outside of the stats queries, so I think adding more cache to nodejs functions is the most important.

**Comment by mchangrh** [comment]
> maybe it would be worth making it not clear cache in cases that don't matter? Voting on a locked segment or a video with locked categories.

this wouldn't work without overlap/ similarity calculations - locked segments exist alongside unlocked segments

**Comment by mchangrh** [comment]
> Postgres cpu hasn't really been an issue anymore outside of the stats queries, so I think adding more cache to nodejs functions is the more useful

I'll have a look through some of the functions and see where optimizations can be made but redis should be faster than postgres therefore... profit

**Comment by ajayyy** [comment]
Maybe we can use this new query cache I made for ratings

https://github.com/ajayyy/SponsorBlockServer/blob/bd3e38fe407819d7bc8928fbc819a365b0d6d393/src/utils/queryCacher.ts#L30-L79

**Comment by ajayyy** [comment]
But if the 60% thing mentioned in https://github.com/ajayyy/SponsorBlockServer/issues/407#issuecomment-980296904 is implemented, it wouldn't be cachable this way anyway

**Comment by mchangrh** [comment]
wouldn't 60% only be for same-category segments?

also is that with node-redis v4 or v3

**Comment by ajayyy** [comment]
To solve issues like this: https://github.com/ajayyy/SponsorBlock/issues/1077

If a self promo and sponsor are almost the same, only one should be served.

**Comment by mchangrh** [comment]
yeah in that case then it wouldn't be able to be split to begin with - with proposed `treat mute as skip` there's no seperation, especially with overlap
