### ISSUE TITLE
[feat] requiredSegments with short hash and videoID

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#411]
Instead of using the full UUID of the segment, lookup the segment with a short hash (prefix + 8 chars)

`https://youtube.com/watch?v=_m1C-tHRGqY#requiredSegment=52b5d1acd`

I hope there won't be that much of a performance impact since it's `LIKE` on a very small set (largest # of segments on a video afair is 91)

**Comment by ajayyy** [comment]
Will a gin index be needed like hashedVideoID? Seemed to be needed for that one otherwise it was super slow.

**Comment by ajayyy** [comment]
Actually, indexes shouldn't be needed since I think the filtering happens in node, not with SQL

**Comment by mchangrh** [comment]
not sure if node filtering would be more efficient than postgres index, either way it would only be on `VideoID=` so maybe an index isn't needed?

**Comment by ajayyy** [comment]
The current system filters via node since otherwise that would mess with query cache

**Comment by mchangrh** [comment]
.take
