### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#420]
Testing HTTP/2 with expressjs

**Comment by mchangrh** [comment]
.take

**Comment by mchangrh** [comment]
native node http2 doesn't work but node-spdy does

**Comment by mchangrh** [comment]
spdy works as a server but it's very difficult to write tests for http/2 and make sure that it's using http/2

**Comment by ajayyy** [comment]
Maybe for tests it could still use http/1.1

**Comment by mchangrh** [comment]
yep, I don't want to test all of the routes with /2 since anyone with misconfigured ca/key will  just get bombarded with irrelevant errors a mock for status 200 and not `httpMajorVersion` 1 should be enough

**Comment by mchangrh** [comment]
unfortunately nginx doesn't proxy http/2, it only supports http/2 server push. 

I'll still configure the PR but it won't be that useful in production

**Comment by mchangrh** [comment]
will close PR. The added dependencies and (currently) minimal benefit combined with the jank nature of HTTP/2 and node isn't worth it.

If spdy comes to stable and http/2 is widely supported, adding http2 with node-spdy should be as simple as

```ts
    spdy.createServer(config.spdy, app).listen(config.port, callback)
```
