### ISSUE TITLE
Improve nginx error messages to not send back HTML

### ISSUE THREAD

**Issue by eladkarako** [ajayyy/SponsorBlockServer#443]
<img width="397" alt="2021-12-10_170649" src="https://user-images.githubusercontent.com/415238/145595813-6d543b22-a344-4d09-828b-24ab1567ae0e.png">

<hr/>
<details><summary>edit.</summary>
just felt I should mention that plain text or even just the numeric value from the HTTP status are probably the safest way to acknowledge errors. 
and just in-case you are considering something like a dialog alternative to alert (or even YT own polymer's dialogs) to render raw HTML from your server, please don't.

rendering external raw HTML is pretty much `eval`, 
and potentially can be used in-case the servers would be compromised to "drink up"
a lot of private information from the client-side.
</details>

**Comment by mchangrh** [comment]
![image](https://user-images.githubusercontent.com/15132783/148629389-a11c1eba-b6a3-4619-951a-b2d7c397deaa.png)

this actually looks awful LOL
