### ISSUE TITLE
api.sponsor.ajay.app SSL-certificate expired

### ISSUE THREAD

**Issue by gzzz** [ajayyy/SponsorBlockServer#470]
SSL-certificate expired 12 May, connections fails.

```
issuer= /C=AT/O=ZeroSSL/CN=ZeroSSL RSA Domain Secure Site CA
subject= /CN=sponsor.ajay.app
notBefore=Feb 10 00:00:00 2022 GMT
notAfter=May 11 23:59:59 2022 GMT
```

Please, renew it.

**Comment by ajayyy** [comment]
yes, please use sponsor.ajay.app for now

**Comment by gzzz** [comment]
Unfortunately, `sponsor.ajay.app` was inaccessible for me.
`api.sponsor.ajay.app` worked fine as replacement till today.

Now checked `sponsor.ajay.app` – became accessible, will use it.

**Comment by ajayyy** [comment]
If you are in russia, a vpn to another country would fix it

**Comment by gzzz** [comment]
Yes, but VPN can't be used all time.
