### ISSUE TITLE
importing csv db

### ISSUE THREAD

**Issue by 1Euro7Cent** [ajayyy/SponsorBlockServer#478]
I am trying to host my own server. And I want to have the public db in there. The server works but there is no db. I don't know what to do with the CSV files. Please help me with that.

I tried simply putting them in the databases folder. That seems not to work.

**Comment by ajayyy** [comment]
There is no built in functionality, I can keep this open in case someone wants to do that.

Right now, you can manually use postgres `COPY` statement https://www.postgresqltutorial.com/postgresql-tutorial/import-csv-file-into-posgresql-table/

**Comment by ajayyy** [comment]
https://github.com/mchangrh/sb-mirror/ is focused on creating mirrors

**Comment by 1Euro7Cent** [comment]
the problem is i cannot use docker

**Comment by 1Euro7Cent** [comment]
> > the problem is i cannot use docker
> 
> the containers are almost all barebones - dockerfiles are mostly setup - any actual logic or execution is in `docker-entrypoint.sh`

I cannot use docker because of not being able to use docker. The problem is not in the actual docker stuff. I just simply cannot use it.
