### ISSUE TITLE
Temporary automod bypass

### ISSUE THREAD

**Issue by mini-bomba** [ajayyy/SponsorBlockServer#494]
Something like temp vip, but for a shorter duration of time and/or on a single video, that only allows the user to bypass the automod/80% rule.
This would be useful for example when the video has less than 20% actual content, to let a regular user submit the segment instead of having a VIP submit for them.
[Initial suggestion/discussion on discord](https://canary.discord.com/channels/603643120093233162/603643180663177220/1010502029745078312)

**Comment by chirag127** [comment]
Well a vip can make that segment instead of giving permission to someone for just one segment.

**Comment by mchangrh** [comment]
should've been implemented in #464 (#453)
