### ISSUE TITLE
look into last-modified as an alternative to duration-check

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlockServer#523]
https://github.com/mchangrh/floatie/blob/main/types/innertube/streamingData.ts#L25

**Comment by erkinalp** [comment]
Do corrections and description edits bump the last modified timestamp?

**Comment by mchangrh** [comment]
> Do [corrections](https://support.google.com/youtube/answer/57404?hl=en&co=GENIE.Platform%3DDesktop) and description edits bump the last modified timestamp?

this technically is part of streamingData, will have to actually look into it instead of theorizing ;)

**Comment by mchangrh** [comment]
does not seem to be awfully reliable as different formats are processed at different times, will reopen if something reliable is found
