### ISSUE TITLE
Docker images are currently being pushed as the same tag

### ISSUE THREAD

**Issue by shahoob** [ajayyy/SponsorBlockServer#525]
It wouldn't be ideal if someone had to manually find an untagged images with the version they want to use.

It will also propose a risk when a new breaking change (v2) is being pushed to the same tag.

The `latest` tag can still be used though, 
but I would propose changes to introduce new tags for each major version's latest minor/patch update. (`v1`, `v2`, etc.)
When for example you make a breaking update (v2.0.0), The image associated with the last commit of that exact version number **must** not be pushed to `v1` and should be instead to `latest` and `v2`.

It would also be nice to also have tags for minor and patch versions. (`v1.0`, `v1.0.34`, etc.)

**Comment by mchangrh** [comment]
SponsorBlockServer does not follow semver, you can also pull by raw SHA hash

https://github.com/ajayyy/SponsorBlockServer/pkgs/container/sb-server/versions?filters%5Bversion_type%5D=untagged

**Comment by shahoob** [comment]
understandable, i will close this issue
have a nice day
