### ISSUE TITLE
Change occurred endpoint

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#527]
Right now refetch if not found uses way too much bandwidth due to randomizing of the results breaking the etag cache header 304. A better option would be to have a change occurred endpoint

**Comment by mchangrh** [comment]
since all the mechanisms I thought up of were too convoluted, Instead I think we should use  the if-modified-since response fields built into HTTP for caching in tandem with 304 Not Modified

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#if-modified-since

**Comment by mchangrh** [comment]
.take
