### ISSUE TITLE
Allow DeArrow hashes to be more than 4 characters

### ISSUE THREAD

**Issue by ChunkyProgrammer** [ajayyy/SponsorBlockServer#551]
Allow DeArrow hashes to be more than 4 characters or update api docs

According to the api docs, "sha256HashPrefix is a hash of the YouTube videoID. It should be the first 4 - 32 characters (4 is recommended)" https://wiki.sponsor.ajay.app/w/API_Docs/DeArrow

But if the hash is more than 4 then there is an error.

See:
https://github.com/ajayyy/SponsorBlockServer/blob/fa6919a1d0289a0683e72a3dc66a970b844a8626/src/routes/getBranding.ts#L285

**Comment by ajayyy** [comment]
docs updated
