### ISSUE TITLE
SponsorBlock is muting segments instead of skipping them

### ISSUE THREAD

**Issue by Ash3781** [ajayyy/SponsorBlockServer#552]
Hey, first of all great work for such an project.
I have no idea what i did, but now sponsorblock mutes segments, and not skips them, as i told it to do in it's settings... thank you for any help in advance :3
edit: i have just tried resetting the extension to it's default, and it still mutes segments instead of skipping them. also to clarify; it skipped segments before

**Comment by ajayyy** [comment]
Is this only on a specific video?

**Comment by Ash3781** [comment]
so far i have only noticed it on one video, the segment was an interaction reminder, sponsor segments seem to be skipped on other videos, or at least those i just tried

**Comment by ajayyy** [comment]
This is not a bug. This is a different type of segment. You can submit segments as a mute segment when there is something important on screen so it cannot be skipped.
