### ISSUE TITLE
Replacing Express with uWebSockets.js

### ISSUE THREAD

**Issue by SashaXser** [ajayyy/SponsorBlockServer#573]
I propose to replace Express with uWebSockets.js in the project to improve the performance, scalability and reliability of web server. 
uWebSockets.js is compatible with most of the Express middleware and routing features, so migration should not be too difficult.
Perhaps this can help make the process easier: 
[uWebSockets-express](https://github.com/colyseus/uWebSockets-express)

**Comment by mchangrh** [comment]
the name is misleading 😆 I believe we do still want to support attachment() for csv downloads without nginx and we have some custom middleware (for CORS and ETAGs) that should be relatively easy to port. 

[uWebSockets](https://github.com/uNetworking/uWebSockets.js/)

**Comment by mchangrh** [comment]
Ah, its only installable with bun.

**Comment by SashaXser** [comment]
> Ah, it's only installable with bun.

Is that a problem? Almost anything can be than better nodejs, even deno (but that's another story).

**Comment by mchangrh** [comment]
bun lacks a lot of compatibility and will require us to rebuild or inflate our docker containers. Bun [struggles with windows](https://github.com/oven-sh/bun/issues/43) and [lacks musl support](https://github.com/oven-sh/bun/issues/918)

Switching frameworks is one thing, switching the entire runtime is another. I've worked with bun previously and it was a pain to get working on windows and required switching to debian from alpine for the docker image since it can't be transposed into node_modules directly.

**Comment by SashaXser** [comment]
> Bun [struggles with windows](https://github.com/oven-sh/bun/issues/43) 


> Switching frameworks is one thing, switching the entire runtime is another. I've worked with bun previously and it was a pain to get working on windows and required switching to debian from alpine for the docker image since it can't be transposed into node_modules directly.

Bun is not very finalized, it has only recently appeared. If uWebSockets.js is not a good fit. I can try to find an alternative for now. But most of them may be on Deno. Well, I'll look for something else.

**Comment by mchangrh** [comment]
[hapi](https://github.com/ajayyy/SponsorBlockServer/issues/361#issuecomment-949333314) was suggested previously and I've recently done a project with it. To be honest we have bigger issues with our stack, chasing down the most optimized, opinionated and squeezing out that extra 10% of performance imo isn't worth the widespread popularity, stability and compatibility that comes with Express. I've also worked with Koa, Fastify and Next.js before and I don't really see enough red flags to switch yet. 

The one true optimal web framework is reading the TCP stream with regex 😍
