### ISSUE TITLE
add `ETag` and `Cache-Control` headers to allow clients to cache segments

### ISSUE THREAD

**Issue by dyc3** [ajayyy/SponsorBlockServer#576]
## Problem

Requests to `GET /api/skipSegments` do not include `ETag` nor `Cache-Control` headers. It appears that the sponsorblock server does already set the `ETag` header. However, after making a request in firefox going through cloudflare, the header appears to be missing.

https://github.com/ajayyy/SponsorBlockServer/blob/591b342855f7f8b39d82543280db7c26c262061c/src/routes/getSkipSegments.ts#L400-L402

<details>

<summary>HTTP Headers for a request to `GET /api/skipSegments` in firefox</summary>

Response:
```
X-Firefox-Spdy: h2
access-control-allow-headers: Content-Type, If-None-Match
access-control-allow-methods: GET, POST, OPTIONS, DELETE
access-control-allow-origin: *
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
cf-ray: 8634c5b75d804414-EWR
content-encoding: br
content-security-policy: script-src 'none'; object-src 'none'
content-type: application/json; charset=utf-8
date: Tue, 12 Mar 2024 15:21:09 GMT
sbserver-host: sb-server-deployment-df4b9647-tp5xk
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains
x-cache-status: MISS
x-powered-by: Express
```

Request:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Host: sponsor.ajay.app
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
TE: trailers
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0
```

</details>

Strangely, I tried the same request with `curl` and was able to find the `ETag` header. I suspect this could be a really weird optimization that cloudflare does for responses that don't include the `Cache-Control` header.

Additionally, the `Cache-Control` header is not being set. This technically [means that clients are free to implement whatever cache policy they want](https://stackoverflow.com/questions/62838739/browser-caching-request-response-without-any-cache-control-header). However in practice, I've found this generally will prevent browsers from caching the request, regardless of the presence of the `ETag` header, and they will not use `If-None-Match`.

## Context

HTTP specifies some headers to allow servers to convey caching requirements to clients, and clients to indicate to servers that they have a specific resource cached. For example, if a server includes a `ETag` header and a `Cache-Control: public,max-age=3600,immutable` header, the client should not make another request with the same query for 3600 seconds. After 3600 seconds, if the client makes another request with the same query, the client will include a `If-None-Match` header in the request. If the server determines that the resource has not been modified, it can respond with a `304` with no response body to indicate to the client that the cached resource is still fresh.

```mermaid
---
title: Example of HTTP conditional requests
---
sequenceDiagram
    Client->>+Server: GET /foo
    Server->>-Client: 200 OK, ETag: <A>, Cache-Control: ...
    note over Client,Server: Time Passes
    alt if server's resource is still fresh
    Client->>+Server: GET /foo, If-None-Match: <A>
    Server->>-Client: 304 Not Modified
    note over Client: Client uses cached resource
    else if server's resource has changed
    Client->>+Server: GET /foo, If-None-Match: <A>
    Server->>-Client: 200 OK, ETag: <A>, Cache-Control: ...
    note over Client: Client caches new version of resource
    end
```

See:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1632

**Comment by ajayyy** [comment]
Fixed
