### ISSUE TITLE
Restrictions on what characters a username can contain.

### ISSUE THREAD

**Issue by Joe-Dowd** [ajayyy/SponsorBlockServer#58]
The API doesn't currently restrict which characters a username can contain. 
For example userId a5681b9905d953ff3bc6dfebda7c1fb1072b5c18e1fd3e201c33f107c9fe73b9
The username should be restricted to a set of characters.

Also it looks like the videoId has no constraints either (and is also a non-hashed text input) - this one should be easier to define as it's already defined by youtube.

**Comment by ajayyy** [comment]
Are there any specific reasons to do this to usernames?

**Comment by Joe-Dowd** [comment]
There are times where you display usernames, such as on the stats page - which could lead to XSS issues.

**Comment by ajayyy** [comment]
Because I use innerText instead of innerHTML, it is not needed. If I did
clean them out, then I'd have to put them back on the website.

**Comment by Joe-Dowd** [comment]
Protecting against it from the client side isn't good practice - others could use the API too.

**Comment by Joe-Dowd** [comment]
Also, the username isn't used in any outgoing requests, so the restriction wouldn't cause an issue for anybody with a legacy username.

**Comment by ajayyy** [comment]
I feel that forcing anyone using the API to replace the escaped characters after using it could be annoying as well.

**Comment by Joe-Dowd** [comment]
What do you mean by that sorry?

**Comment by Joe-Dowd** [comment]
You don't need to force people using the api to replace escaped characters - I was thinking more whitelisting certain characters - but either way is good.

**Comment by ajayyy** [comment]
I think is important to allow any characters be used in the display name, so they would have to be escaped.

**Comment by MRuy** [comment]
Dont escape data for storage, thats why a prepare statement is used in the SQL query.
We dont know where the data will be used so it will be transfered and the client has to make sure its handled correctly for the intended purpose.

If someone is using it on the web he has to escape it.
Using it with a Android or iOS app it has not to be HTML escaped.
